name: JsonSchemaLinter
on:
 push:
  branches: lab_work_11
jobs:
 json_linter_test:
  runs-on: ubuntu-latest
  steps:
  - name: checkout
    uses: "actions/checkout@v3"
  - name: Start JsonSchemaLinter
    run: |
      npm i -g @prantlf/jsonlint
      jsonlint $GITHUB_WORKSPACE/DataSchema.json
